name: PR workflow on master branch

on:
  pull_request:
    branches: [ master ]

jobs:
  analyze_with_flutter:
    name: Analyze PR using Dart latest version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with: 
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
        
      - name: Verify formatting
        run: dart format .

      - name: Analyze package warnings
        run: flutter pub publish --dry-run

      - name: Run tests
        run: flutter test
  
  analyze_with_pana:
    name: Analyze PR using Pana latest version
    needs: [analyze_with_dart]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      
      - name: Install dependencies
        run: dart pub get
      
      - name: Install Pana
        run: dart pub global activate pana
      
      - name: Run pana
        run: $HOME/.pub-cache/bin/pana .